// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamSchedule.Markov2;

#nullable disable

namespace StreamSchedule.Migrations.Markov
{
    [DbContext(typeof(MarkovContext))]
    partial class MarkovContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("StreamSchedule.Markov2.Data.Token", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tokens");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StreamSchedule.Markov2.Data.TokenPair", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextTokenID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("TokenPairs");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("StreamSchedule.Markov2.Data.TokenOnline", b =>
                {
                    b.HasBaseType("StreamSchedule.Markov2.Data.Token");

                    b.ToTable("TokensOnline");
                });

            modelBuilder.Entity("StreamSchedule.Markov2.Data.TokenPairOnline", b =>
                {
                    b.HasBaseType("StreamSchedule.Markov2.Data.TokenPair");

                    b.ToTable("TokenPairsOnline");
                });

            modelBuilder.Entity("StreamSchedule.Markov2.Data.TokenOnline", b =>
                {
                    b.HasOne("StreamSchedule.Markov2.Data.Token", null)
                        .WithOne()
                        .HasForeignKey("StreamSchedule.Markov2.Data.TokenOnline", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StreamSchedule.Markov2.Data.TokenPairOnline", b =>
                {
                    b.HasOne("StreamSchedule.Markov2.Data.TokenPair", null)
                        .WithOne()
                        .HasForeignKey("StreamSchedule.Markov2.Data.TokenPairOnline", "ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
